import "server-only";

/**
 * In-memory per-IP rate limiter for the Instant Poll API routes.
 *
 * Trade-offs, in one paragraph so nobody thinks we forgot about them:
 *
 * The limiter uses a Map inside the Node.js process. Each Vercel
 * serverless instance therefore has its own bucket state. Under heavy
 * load Vercel will spin up multiple instances and the "20 polls per
 * IP per hour" becomes effectively "20 per IP per instance per hour"
 * — a client hitting different edge locations can slip past the cap.
 * That's acceptable for a public-write consumer tool where abuse is
 * casual (spam bots, curious teenagers), not systematic. If the tool
 * ever attracts systematic abuse, swap this file's implementation for
 * Upstash Redis or Vercel KV without touching any of the callers.
 *
 * IPs are hashed with a per-process salt that rotates on cold start.
 * The Map keys therefore never contain raw IP addresses — the salt is
 * random 256-bit hex generated by crypto.getRandomValues on first use
 * and lives only in the process's memory.
 */

interface Bucket {
  count: number;
  /** Millisecond timestamp when the window resets. */
  resetAt: number;
}

const buckets = new Map<string, Bucket>();

/** Sweep expired buckets periodically to keep the Map bounded. Guarded
 *  against duplicate timers under Next's dev hot-reload. */
const CLEANUP_INTERVAL_MS = 60_000;
const CLEANUP_KEY = "__pollRateLimitTimer";
type GlobalWithTimer = typeof globalThis & { [CLEANUP_KEY]?: NodeJS.Timeout };
const g: GlobalWithTimer = globalThis;
if (!g[CLEANUP_KEY]) {
  g[CLEANUP_KEY] = setInterval(() => {
    const now = Date.now();
    for (const [k, b] of buckets) {
      if (b.resetAt < now) buckets.delete(k);
    }
  }, CLEANUP_INTERVAL_MS);
  // .unref() so the interval doesn't hold the Node process alive if
  // that ever mattered (Vercel serverless doesn't care, but future
  // Node targets might).
  if (typeof g[CLEANUP_KEY]?.unref === "function") g[CLEANUP_KEY].unref();
}

export interface RateLimitResult {
  ok: boolean;
  /** Seconds until the client can retry. Only set when ok=false. */
  retryAfterSec?: number;
  /** How many hits remain in the current window. */
  remaining: number;
}

/**
 * Consume one hit against the bucket keyed by `key`. Sliding fixed
 * window — after `windowMs` the count resets. Callers get
 * `retryAfterSec` when denied and pass it to the client as a
 * Retry-After header.
 */
export function checkRateLimit(
  key: string,
  max: number,
  windowMs: number
): RateLimitResult {
  const now = Date.now();
  const bucket = buckets.get(key);
  if (!bucket || bucket.resetAt < now) {
    buckets.set(key, { count: 1, resetAt: now + windowMs });
    return { ok: true, remaining: max - 1 };
  }
  if (bucket.count >= max) {
    return {
      ok: false,
      retryAfterSec: Math.ceil((bucket.resetAt - now) / 1000),
      remaining: 0,
    };
  }
  bucket.count++;
  return { ok: true, remaining: max - bucket.count };
}

/**
 * Extract the client IP from the request headers. Prefers Vercel's
 * signed `x-vercel-forwarded-for` when available; falls back to the
 * first hop of `x-forwarded-for` and finally `x-real-ip`. Returns
 * "unknown" when nothing works — that fallback shares a single bucket
 * across all "unknown" callers, which is the correct behaviour (still
 * capped, no free rides).
 */
export function getClientIp(headers: Headers): string {
  const vercelIp = headers.get("x-vercel-forwarded-for");
  if (vercelIp) return vercelIp.trim();
  const forwarded = headers.get("x-forwarded-for");
  if (forwarded) {
    const first = forwarded.split(",")[0]?.trim();
    if (first) return first;
  }
  const realIp = headers.get("x-real-ip");
  if (realIp) return realIp.trim();
  return "unknown";
}

// ── IP hashing ─────────────────────────────────────────────────────────

let cachedSalt: string | null = null;
function getIpSalt(): string {
  if (cachedSalt) return cachedSalt;
  const buf = new Uint8Array(32);
  crypto.getRandomValues(buf);
  let out = "";
  for (let i = 0; i < buf.length; i++) out += buf[i].toString(16).padStart(2, "0");
  cachedSalt = out;
  return cachedSalt;
}

/**
 * SHA-256(salt || ip) — hex. The salt rotates whenever the process
 * cold-starts, which functions as a lenient "reset all counters"
 * signal from Vercel's perspective. That's fine: cold starts happen
 * every deploy and after minutes of inactivity, both of which are
 * privacy-positive for the same reason they're bad for cache warmth.
 */
export async function hashIp(ip: string): Promise<string> {
  const input = `${getIpSalt()}|${ip}`;
  const bytes = new TextEncoder().encode(input);
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  const arr = new Uint8Array(digest);
  let out = "";
  for (let i = 0; i < arr.length; i++) out += arr[i].toString(16).padStart(2, "0");
  return out;
}
