export interface Tool {
  id: string;
  name: string;
  description: string;
  longDescription: string;
  category: string;
  icon: string;
  href: string;
  /** User-facing URL for the standalone tool site. Opens in a new tab. */
  externalHref: string | null;
  /** URL for the in-page iframe embed. Often the same as `externalHref`,
   *  but can differ if the standalone site has a dedicated embed view
   *  (e.g. /embed) without a header/footer. Null = no embed available. */
  embedUrl: string | null;
  keywords: string[];
  trending: boolean;
  new: boolean;
  featured: boolean;
  monthlySearches: number;
  cpc: number;
  relatedTools: string[];
}

export const TOOLS: Tool[] = [
  {
    id: "loan-calculator",
    name: "Loan Calculator",
    description:
      "Free loan calculator to estimate monthly payments, interest, and total cost across any loan term and rate.",
    longDescription:
      "Calculate monthly loan payments, total interest, and full amortization schedules for personal, auto, student, or business loans. Compare interest rates, terms, and down payments side-by-side and download a printable schedule. Works for US, UK, Canadian, and EU borrowers with full currency support.",
    category: "Finance Tools",
    icon: "Banknote",
    href: "/tools/loan-calculator",
    // Built static export lives at public/embeds/loan-calculator/.
    externalHref:
      process.env.NEXT_PUBLIC_TOOL_LOAN_URL ?? "/embeds/loan-calculator/tools/loan-calculator/",
    embedUrl:
      process.env.NEXT_PUBLIC_TOOL_LOAN_URL ?? "/embeds/loan-calculator/tools/loan-calculator/",
    keywords: [
      "loan calculator",
      "monthly payment calculator",
      "personal loan calculator",
      "auto loan calculator",
      "amortization schedule",
      "interest calculator",
    ],
    trending: true,
    new: false,
    featured: true,
    monthlySearches: 2200000,
    cpc: 35,
    relatedTools: ["mortgage-calculator", "compound-interest-calculator", "tax-calculator"],
  },
  {
    id: "mortgage-calculator",
    name: "Mortgage Calculator",
    description:
      "Estimate monthly mortgage payments, PMI, taxes, and insurance with a free mortgage affordability calculator.",
    longDescription:
      "Plan home purchases with a complete mortgage calculator that includes principal, interest, property tax, homeowners insurance, PMI, and HOA fees. Compare 15-year vs 30-year terms, see amortization schedules, and check affordability based on income and debt-to-income ratio.",
    category: "Finance Tools",
    icon: "Home",
    href: "/tools/mortgage-calculator",
    // Mortgage Calculator is bundled inside the Loan-Calculator static export.
    externalHref:
      process.env.NEXT_PUBLIC_TOOL_MORTGAGE_URL ??
      "/embeds/loan-calculator/tools/mortgage-calculator/",
    embedUrl:
      process.env.NEXT_PUBLIC_TOOL_MORTGAGE_URL ??
      "/embeds/loan-calculator/tools/mortgage-calculator/",
    keywords: [
      "mortgage calculator",
      "home loan calculator",
      "PITI calculator",
      "mortgage affordability",
      "refinance calculator",
    ],
    trending: true,
    new: false,
    featured: true,
    monthlySearches: 2700000,
    cpc: 35,
    relatedTools: ["loan-calculator", "tax-calculator", "salary-calculator"],
  },
  {
    id: "bmi-calculator",
    name: "BMI Calculator",
    description:
      "Calculate Body Mass Index instantly in metric or imperial units with healthy range guidance for adults.",
    longDescription:
      "Measure body mass index with support for both metric (kg/cm) and imperial (lb/ft-in) units. See WHO healthy range categories, ideal weight targets, and personalized guidance based on age and gender. Mobile-friendly and works offline.",
    category: "Health Tools",
    icon: "HeartPulse",
    href: "/tools/bmi-calculator",
    externalHref: process.env.NEXT_PUBLIC_TOOL_BMI_URL ?? "/embeds/bmi-calculator/",
    embedUrl: process.env.NEXT_PUBLIC_TOOL_BMI_URL ?? "/embeds/bmi-calculator/",
    keywords: [
      "BMI calculator",
      "body mass index",
      "healthy weight calculator",
      "BMI metric",
      "BMI imperial",
    ],
    trending: true,
    new: false,
    featured: true,
    monthlySearches: 1800000,
    cpc: 18,
    relatedTools: ["calorie-calculator", "macros-calculator", "water-intake-calculator"],
  },
  {
    id: "percentage-calculator",
    name: "Percentage Calculator",
    description:
      "Calculate percentages, percent change, percent off, and percent of any number with a free online tool.",
    longDescription:
      "Solve every percentage problem in seconds: percent of a number, percent change, percent increase or decrease, tip and discount math, and grade calculations. Includes step-by-step explanations so you can learn the formula, not just the answer.",
    category: "Calculator Tools",
    icon: "Percent",
    href: "/tools/percentage-calculator",
    externalHref:
      process.env.NEXT_PUBLIC_TOOL_PERCENTAGE_URL ?? "/embeds/percentage-calculator/",
    embedUrl:
      process.env.NEXT_PUBLIC_TOOL_PERCENTAGE_URL ?? "/embeds/percentage-calculator/",
    keywords: [
      "percentage calculator",
      "percent change calculator",
      "percent off calculator",
      "discount calculator",
      "percentage formula",
    ],
    trending: true,
    new: false,
    featured: true,
    monthlySearches: 1400000,
    cpc: 8,
    relatedTools: ["tip-calculator", "tax-calculator", "gpa-calculator"],
  },
  {
    id: "age-calculator",
    name: "Age Calculator",
    description:
      "Calculate exact age in years, months, weeks, and days between any two dates with timezone-aware accuracy.",
    longDescription:
      "Find precise age or duration between any two dates down to the day, hour, and minute. Includes leap-year handling, next-birthday countdown, and zodiac/Chinese zodiac display. Useful for HR, legal forms, and birthday planning.",
    category: "Calculator Tools",
    icon: "CalendarDays",
    href: "/tools/age-calculator",
    externalHref: process.env.NEXT_PUBLIC_TOOL_AGE_URL ?? "/embeds/age-calculator/",
    embedUrl: process.env.NEXT_PUBLIC_TOOL_AGE_URL ?? "/embeds/age-calculator/",
    keywords: [
      "age calculator",
      "date difference calculator",
      "birthday calculator",
      "years months days",
    ],
    trending: false,
    new: false,
    featured: false,
    monthlySearches: 900000,
    cpc: 4,
    relatedTools: ["percentage-calculator", "gpa-calculator", "tip-calculator"],
  },
  {
    id: "word-counter",
    name: "Word Counter",
    description:
      "Count words, characters, sentences, paragraphs, and reading time for essays, articles, and social posts.",
    longDescription:
      "Instantly analyze any text for word count, character count (with and without spaces), sentence and paragraph totals, reading time, speaking time, and keyword density. Perfect for students, writers, marketers, and SEO specialists.",
    category: "Text Tools",
    icon: "Type",
    href: "/tools/word-counter",
    // Static HTML lives in /public/embeds/word-counter (same-origin).
    // The rewrite rule in next.config.js maps this directory path to its
    // index.html automatically, so the URL stays clean.
    externalHref: process.env.NEXT_PUBLIC_TOOL_WORD_URL ?? "/embeds/word-counter/",
    embedUrl: process.env.NEXT_PUBLIC_TOOL_WORD_URL ?? "/embeds/word-counter/",
    keywords: [
      "word counter",
      "character counter",
      "text analyzer",
      "reading time calculator",
      "keyword density",
    ],
    trending: true,
    new: false,
    featured: false,
    monthlySearches: 1100000,
    cpc: 3,
    relatedTools: ["character-counter", "case-converter", "text-diff-checker"],
  },
  {
    id: "character-counter",
    name: "Character Counter",
    description:
      "Count characters with and without spaces for tweets, SEO meta tags, SMS, and bio fields.",
    longDescription:
      "Real-time character counting with platform presets for X (Twitter), LinkedIn, Instagram bios, SMS messages, and meta descriptions. Live limit indicators, byte count for UTF-8, and copy-friendly export.",
    category: "Text Tools",
    icon: "Hash",
    href: "/tools/character-counter",
    externalHref: null,
    embedUrl: null,
    keywords: ["character counter", "letter counter", "tweet counter", "bio counter"],
    trending: false,
    new: false,
    featured: false,
    monthlySearches: 450000,
    cpc: 2,
    relatedTools: ["word-counter", "case-converter", "meta-tag-generator"],
  },
  {
    id: "case-converter",
    name: "Case Converter",
    description:
      "Convert text to uppercase, lowercase, title case, sentence case, camelCase, and snake_case instantly.",
    longDescription:
      "One-click conversion between every common text case: UPPERCASE, lowercase, Title Case, Sentence case, camelCase, PascalCase, snake_case, kebab-case, and CONSTANT_CASE. Preserves emojis and punctuation, with batch and clipboard support.",
    category: "Text Tools",
    icon: "CaseSensitive",
    href: "/tools/case-converter",
    externalHref: null,
    embedUrl: null,
    keywords: ["case converter", "uppercase to lowercase", "title case", "snake case converter"],
    trending: false,
    new: true,
    featured: false,
    monthlySearches: 320000,
    cpc: 2,
    relatedTools: ["word-counter", "character-counter", "slug-generator"],
  },
  {
    id: "text-diff-checker",
    name: "Text Diff Checker",
    description:
      "Compare two text blocks side-by-side and highlight added, removed, and changed lines instantly.",
    longDescription:
      "Diff any two pieces of text with line-by-line, word-by-word, and character-level highlights. Ideal for proofreading drafts, comparing contract revisions, debugging configs, and reviewing translations. Privacy-first: everything runs locally.",
    category: "Text Tools",
    icon: "GitCompare",
    href: "/tools/text-diff-checker",
    externalHref: null,
    embedUrl: null,
    keywords: ["text diff", "compare text", "diff checker", "text comparison tool"],
    trending: false,
    new: true,
    featured: false,
    monthlySearches: 220000,
    cpc: 3,
    relatedTools: ["word-counter", "json-formatter", "case-converter"],
  },
  {
    id: "pdf-converter",
    name: "PDF Converter",
    description:
      "Convert PDFs to Word, Excel, JPG, or PNG and merge, split, or compress PDF files online for free.",
    longDescription:
      "All-in-one PDF toolkit: convert PDF to Word, Excel, PowerPoint, JPG, or PNG, and merge, split, rotate, or compress documents. OCR available for scanned files. Files are processed in-browser when possible and auto-deleted from servers within an hour.",
    category: "Productivity Tools",
    icon: "FileText",
    href: "/tools/pdf-converter",
    // PDF_Converter has a server `/api/convert` route that doesn't ship in
    // the static export — the UI loads but conversion calls will 404.
    // Run the standalone PDF_Converter dev server alongside utilityapps and
    // set NEXT_PUBLIC_TOOL_PDF_URL to that origin if you need full function.
    externalHref: process.env.NEXT_PUBLIC_TOOL_PDF_URL ?? "/embeds/pdf-converter/",
    embedUrl: process.env.NEXT_PUBLIC_TOOL_PDF_URL ?? "/embeds/pdf-converter/",
    keywords: [
      "PDF converter",
      "PDF to Word",
      "PDF to Excel",
      "merge PDF",
      "compress PDF",
      "split PDF",
    ],
    trending: true,
    new: false,
    featured: false,
    monthlySearches: 1600000,
    cpc: 9,
    relatedTools: ["convert-from-jpg", "qr-code-generator", "compress-image"],
  },
  {
    id: "qr-code-generator",
    name: "QR Code Generator",
    description:
      "Generate custom QR codes for URLs, WiFi, vCards, and payments with logos, colors, and high-resolution export.",
    longDescription:
      "Create branded QR codes for URLs, WiFi networks, vCards, SMS, email, and payment links. Customize colors, add a logo, choose error-correction level, and download as PNG, SVG, or PDF up to 4096px. Free for personal and commercial use.",
    category: "Productivity Tools",
    icon: "QrCode",
    href: "/tools/qr-code-generator",
    externalHref: null,
    embedUrl: null,
    keywords: ["QR code generator", "custom QR code", "QR code with logo", "WiFi QR code"],
    trending: true,
    new: false,
    featured: false,
    monthlySearches: 1300000,
    cpc: 7,
    relatedTools: ["password-generator", "pdf-converter", "meta-tag-generator"],
  },
  {
    id: "password-generator",
    name: "Password Generator",
    description:
      "Create strong, random passwords with adjustable length, symbols, and pronounceable options. 100% offline.",
    longDescription:
      "Generate cryptographically secure random passwords with full control over length, character classes, and exclusions. Optional pronounceable mode, passphrase mode (Diceware-style), and bulk export. All generation happens locally — nothing is logged or transmitted.",
    category: "Developer Tools",
    icon: "KeyRound",
    href: "/tools/password-generator",
    externalHref: null,
    embedUrl: null,
    keywords: ["password generator", "secure password", "random password", "passphrase generator"],
    trending: false,
    new: false,
    featured: false,
    monthlySearches: 540000,
    cpc: 5,
    relatedTools: ["qr-code-generator", "json-formatter", "base64-encoder"],
  },
  {
    id: "json-formatter",
    name: "JSON Formatter & Validator",
    description:
      "Format, validate, minify, and convert JSON with syntax error highlighting and JSONPath query support.",
    longDescription:
      "Pretty-print or minify JSON, validate against JSON Schema, and inspect huge payloads with collapsible tree view, search, and JSONPath queries. Convert between JSON, YAML, CSV, and XML in one click. Works with massive files — no server roundtrips.",
    category: "Developer Tools",
    icon: "Braces",
    href: "/tools/json-formatter",
    externalHref: null,
    embedUrl: null,
    keywords: ["JSON formatter", "JSON validator", "JSON beautifier", "JSON to YAML", "JSONPath"],
    trending: false,
    new: false,
    featured: false,
    monthlySearches: 480000,
    cpc: 4,
    relatedTools: ["base64-encoder", "password-generator", "text-diff-checker"],
  },
  {
    id: "base64-encoder",
    name: "Base64 Encoder & Decoder",
    description:
      "Encode and decode Base64 strings, files, and images instantly with URL-safe and standard variants.",
    longDescription:
      "Convert text, files, and images to and from Base64 with one click. Supports standard, URL-safe, and MIME variants, and handles both UTF-8 strings and binary blobs. All processing is local — perfect for handling tokens, secrets, and PII safely.",
    category: "Developer Tools",
    icon: "Binary",
    href: "/tools/base64-encoder",
    externalHref: null,
    embedUrl: null,
    keywords: ["base64 encoder", "base64 decoder", "encode base64", "decode base64"],
    trending: false,
    new: false,
    featured: false,
    monthlySearches: 360000,
    cpc: 3,
    relatedTools: ["json-formatter", "password-generator", "url-encoder"],
  },
  {
    id: "url-encoder",
    name: "URL Encoder & Decoder",
    description:
      "Percent-encode and decode URLs, query parameters, and components for safe links and API requests.",
    longDescription:
      "Encode or decode entire URLs or just components (path, query, fragment) using RFC-3986 percent encoding. Inspect and edit query parameters in a friendly grid view, then export the rebuilt URL. Great for debugging redirects and API integrations.",
    category: "Developer Tools",
    icon: "Link2",
    href: "/tools/url-encoder",
    externalHref: null,
    embedUrl: null,
    keywords: ["URL encoder", "URL decoder", "percent encoder", "query string encoder"],
    trending: false,
    new: true,
    featured: false,
    monthlySearches: 210000,
    cpc: 3,
    relatedTools: ["base64-encoder", "json-formatter", "meta-tag-generator"],
  },
  {
    id: "meta-tag-generator",
    name: "Meta Tag Generator",
    description:
      "Generate SEO meta tags, Open Graph, and Twitter Card markup with live preview for Google and social.",
    longDescription:
      "Build complete SEO and social meta tags — title, description, canonical, Open Graph, Twitter Cards, and JSON-LD — with live previews of Google SERP, Facebook, X, and LinkedIn share cards. Includes character-limit guards and best-practice tips.",
    category: "SEO Tools",
    icon: "Tag",
    href: "/tools/meta-tag-generator",
    externalHref: null,
    embedUrl: null,
    keywords: ["meta tag generator", "Open Graph generator", "Twitter Card generator", "SEO meta"],
    trending: true,
    new: false,
    featured: false,
    monthlySearches: 280000,
    cpc: 6,
    relatedTools: ["slug-generator", "character-counter", "json-formatter"],
  },
  {
    id: "slug-generator",
    name: "Slug Generator",
    description:
      "Convert any title or string into a clean, SEO-friendly URL slug with stop-word and locale support.",
    longDescription:
      "Turn article titles, product names, or any string into clean, lowercase, hyphenated slugs. Strips stop words, normalizes accents, supports custom separators, and handles non-Latin scripts (Cyrillic, Greek, CJK transliteration).",
    category: "SEO Tools",
    icon: "Slash",
    href: "/tools/slug-generator",
    externalHref: null,
    embedUrl: null,
    keywords: ["slug generator", "URL slug", "SEO slug", "permalink generator"],
    trending: false,
    new: true,
    featured: false,
    monthlySearches: 95000,
    cpc: 4,
    relatedTools: ["meta-tag-generator", "case-converter", "url-encoder"],
  },
  {
    id: "tip-calculator",
    name: "Tip Calculator",
    description:
      "Split bills and calculate tips by percentage, party size, and country tipping customs in seconds.",
    longDescription:
      "Calculate tips and split checks across any party size with country-aware presets for the US, UK, Canada, and EU. Round-up modes, separate-tax handling, and per-person totals make this the only tip calculator you'll need at the table.",
    category: "Calculator Tools",
    icon: "Receipt",
    href: "/tools/tip-calculator",
    externalHref: null,
    embedUrl: null,
    keywords: ["tip calculator", "bill splitter", "split the check", "gratuity calculator"],
    trending: false,
    new: false,
    featured: false,
    monthlySearches: 410000,
    cpc: 3,
    relatedTools: ["percentage-calculator", "tax-calculator", "currency-converter"],
  },
  {
    id: "gpa-calculator",
    name: "GPA Calculator",
    description:
      "Calculate weighted, unweighted, and cumulative GPA on 4.0 and 5.0 scales for high school and college.",
    longDescription:
      "Track GPA across semesters with support for 4.0 unweighted, 4.0 weighted, 5.0 weighted, and percentage scales. Add letter grades or numeric scores, set credit hours, and project the GPA you need next term to hit a target.",
    category: "Calculator Tools",
    icon: "GraduationCap",
    href: "/tools/gpa-calculator",
    externalHref: null,
    embedUrl: null,
    keywords: ["GPA calculator", "weighted GPA", "cumulative GPA", "college GPA"],
    trending: false,
    new: false,
    featured: false,
    monthlySearches: 520000,
    cpc: 5,
    relatedTools: ["percentage-calculator", "age-calculator", "tip-calculator"],
  },
  {
    id: "tax-calculator",
    name: "Income Tax Calculator",
    description:
      "Estimate federal and state income tax for the US, UK, Canada, and EU with current bracket data.",
    longDescription:
      "Estimate take-home pay after federal, state, and local income tax for the US, UK, Canada, Germany, France, and more. Includes standard deductions, common credits, and self-employment tax — updated each tax year.",
    category: "Finance Tools",
    icon: "Calculator",
    href: "/tools/tax-calculator",
    externalHref: null,
    embedUrl: null,
    keywords: ["tax calculator", "income tax calculator", "take home pay", "tax bracket calculator"],
    trending: true,
    new: false,
    featured: false,
    monthlySearches: 980000,
    cpc: 22,
    relatedTools: ["salary-calculator", "loan-calculator", "mortgage-calculator"],
  },
  {
    id: "salary-calculator",
    name: "Salary Calculator",
    description:
      "Convert hourly, weekly, monthly, and annual salary across currencies with tax and overtime support.",
    longDescription:
      "Compare offers and convert between hourly, weekly, biweekly, monthly, and annual pay across major currencies. Optional withholding, overtime, and benefits cost adjustments produce a true take-home estimate for the US, UK, Canada, and EU.",
    category: "Finance Tools",
    icon: "Wallet",
    href: "/tools/salary-calculator",
    externalHref: null,
    embedUrl: null,
    keywords: ["salary calculator", "hourly to annual", "take home calculator", "paycheck calculator"],
    trending: false,
    new: false,
    featured: false,
    monthlySearches: 760000,
    cpc: 14,
    relatedTools: ["tax-calculator", "loan-calculator", "currency-converter"],
  },
  {
    id: "currency-converter",
    name: "Currency Converter",
    description:
      "Convert between 160+ world currencies with live mid-market rates and multi-amount conversion tables.",
    longDescription:
      "Convert any amount between 160+ currencies using live mid-market exchange rates. View 30/90/365-day historical charts, set rate alerts, and export multi-currency tables for travel budgets and invoicing.",
    category: "Finance Tools",
    icon: "ArrowLeftRight",
    href: "/tools/currency-converter",
    externalHref: null,
    embedUrl: null,
    keywords: ["currency converter", "exchange rate", "USD to EUR", "live forex rates"],
    trending: false,
    new: false,
    featured: false,
    monthlySearches: 1200000,
    cpc: 6,
    relatedTools: ["salary-calculator", "tax-calculator", "tip-calculator"],
  },
  {
    id: "calorie-calculator",
    name: "Calorie Calculator",
    description:
      "Calculate daily calorie needs (TDEE) and calorie targets for weight loss, maintenance, or muscle gain.",
    longDescription:
      "Estimate daily calorie needs using Mifflin-St Jeor and Katch-McArdle equations. Get TDEE based on activity level, then targets for cutting, recomposition, or lean bulking with macro-aware recommendations.",
    category: "Health Tools",
    icon: "Flame",
    href: "/tools/calorie-calculator",
    externalHref: null,
    embedUrl: null,
    keywords: ["calorie calculator", "TDEE calculator", "BMR calculator", "weight loss calculator"],
    trending: true,
    new: false,
    featured: false,
    monthlySearches: 880000,
    cpc: 11,
    relatedTools: ["bmi-calculator", "macros-calculator", "water-intake-calculator"],
  },

  // ── Image Tools (new) ──────────────────────────────────────────────────
  {
    id: "compress-image",
    name: "Image Compressor",
    description:
      "Compress JPG, PNG, SVG, and GIFs while saving space and maintaining quality.",
    longDescription:
      "Shrink JPG, PNG, SVG and GIF files by up to 90% with smart lossy and lossless compression. Bulk-process up to 50 images at once, preview before/after side-by-side, and download a single zip. Runs entirely in your browser — files never upload to a server.",
    category: "Image Tools",
    icon: "FileImage",
    href: "/tools/compress-image",
    externalHref: null,
    embedUrl: null,
    keywords: [
      "compress image",
      "reduce image size",
      "image compression",
      "compress jpg",
      "compress png",
      "compress gif",
      "reduce file size",
      "optimize image",
    ],
    trending: true,
    new: true,
    featured: true,
    monthlySearches: 8_000_000,
    cpc: 5,
    relatedTools: ["resize-image", "convert-to-jpg", "crop-image"],
  },
  {
    id: "resize-image",
    name: "Image Resizer",
    description: "Resize JPG, PNG, SVG and GIF by percent or exact pixel dimensions.",
    longDescription:
      "Resize images to exact pixel dimensions, percentages, or fit-to-width/height while preserving aspect ratio. Supports JPG, PNG, SVG, WEBP, and GIF, with batch processing and presets for common social-media formats. Works locally in your browser.",
    category: "Image Tools",
    icon: "Maximize2",
    href: "/tools/resize-image",
    externalHref: null,
    embedUrl: null,
    keywords: [
      "resize image",
      "image resizer",
      "resize jpg",
      "resize png",
      "change image dimensions",
      "scale image",
      "resize photo",
    ],
    trending: true,
    new: true,
    featured: true,
    monthlySearches: 2_400_000,
    cpc: 4,
    relatedTools: ["compress-image", "crop-image", "rotate-image"],
  },
  {
    id: "crop-image",
    name: "Image Cropper",
    description: "Crop JPG, PNG or GIF with pixel precision or interactive visual editor.",
    longDescription:
      "Crop any image with pixel-perfect numeric inputs or a draggable visual selector. Aspect-ratio presets for Instagram, Facebook, X, and printable sizes. Batch crop multiple images to the same dimensions in one click.",
    category: "Image Tools",
    icon: "Crop",
    href: "/tools/crop-image",
    externalHref: null,
    embedUrl: null,
    keywords: [
      "crop image",
      "crop photo",
      "crop jpg",
      "image cropper",
      "cut image",
      "trim photo",
    ],
    trending: false,
    new: true,
    featured: false,
    monthlySearches: 1_200_000,
    cpc: 3,
    relatedTools: ["resize-image", "rotate-image", "compress-image"],
  },
  {
    id: "convert-to-jpg",
    name: "Convert to JPG",
    description: "Convert PNG, GIF, TIF, PSD, SVG, WEBP, HEIC or RAW images to JPG in bulk.",
    longDescription:
      "Convert any common image format to JPG: PNG, GIF, TIFF, PSD, SVG, WEBP, AVIF, HEIC, and RAW (CR2, NEF, ARW). Bulk-convert hundreds of files at once with adjustable quality. Strips or preserves EXIF metadata at your choice.",
    category: "Image Tools",
    icon: "RefreshCw",
    href: "/tools/convert-to-jpg",
    externalHref: null,
    embedUrl: null,
    keywords: [
      "convert to jpg",
      "png to jpg",
      "webp to jpg",
      "gif to jpg",
      "heic to jpg",
      "image converter",
      "convert image to jpeg",
    ],
    trending: true,
    new: true,
    featured: false,
    monthlySearches: 3_300_000,
    cpc: 4,
    relatedTools: ["convert-from-jpg", "compress-image", "resize-image"],
  },
  {
    id: "convert-from-jpg",
    name: "Convert from JPG",
    description: "Convert JPG to PNG, GIF, WEBP or create animated GIFs from multiple JPGs.",
    longDescription:
      "Convert JPG/JPEG images to PNG (transparent backgrounds via removable solid color), WEBP (smaller files), or GIF. Stitch multiple JPGs into a single animated GIF with adjustable frame timing and looping.",
    category: "Image Tools",
    icon: "ArrowLeftRight",
    href: "/tools/convert-from-jpg",
    externalHref: null,
    embedUrl: null,
    keywords: [
      "jpg to png",
      "jpg to gif",
      "jpg to webp",
      "convert jpg",
      "animated gif maker",
      "jpeg to png",
    ],
    trending: false,
    new: true,
    featured: false,
    monthlySearches: 1_500_000,
    cpc: 3,
    relatedTools: ["convert-to-jpg", "compress-image", "meme-generator"],
  },
  {
    id: "photo-editor",
    name: "Photo Editor",
    description: "Add text, effects, frames and stickers to your photos with our online editor.",
    longDescription:
      "A full in-browser photo editor: add text with custom fonts, apply filters, stickers and frames, draw freehand, and adjust brightness, contrast, saturation, and curves. Layer-based and undo/redo throughout. No watermark on the export.",
    category: "Image Tools",
    icon: "Wand2",
    href: "/tools/photo-editor",
    externalHref: null,
    embedUrl: null,
    keywords: [
      "photo editor",
      "online photo editor",
      "edit photo online",
      "add text to photo",
      "photo effects",
      "free photo editor",
    ],
    trending: false,
    new: true,
    featured: true,
    monthlySearches: 2_700_000,
    cpc: 4,
    relatedTools: ["watermark-image", "meme-generator", "remove-background"],
  },
  {
    id: "upscale-image",
    name: "Image Upscaler",
    description:
      "Enlarge images with AI while maintaining high visual quality. Upscale JPG and PNG images.",
    longDescription:
      "AI-powered upscaler that enlarges images 2x, 4x, or 8x without the blur of standard scaling. Sharpens detail, recovers texture, and works on photos, illustrations, and screenshots. JPG and PNG input; download the high-resolution result.",
    category: "Image Tools",
    icon: "ZoomIn",
    href: "/tools/upscale-image",
    externalHref: null,
    embedUrl: null,
    keywords: [
      "upscale image",
      "enlarge image",
      "increase image resolution",
      "ai image upscaler",
      "upscale photo",
      "enhance image quality",
    ],
    trending: true,
    new: true,
    featured: true,
    monthlySearches: 1_800_000,
    cpc: 6,
    relatedTools: ["remove-background", "photo-editor", "compress-image"],
  },
  {
    id: "remove-background",
    name: "Remove Background",
    description:
      "Automatically remove image backgrounds with AI accuracy. Detect objects and cut backgrounds instantly.",
    longDescription:
      "AI background remover that isolates the foreground subject in seconds — people, products, animals, or any object. Returns a transparent PNG ready for design use. Refine edges with a brush tool for the trickiest hair and fur.",
    category: "Image Tools",
    icon: "Eraser",
    href: "/tools/remove-background",
    externalHref: null,
    embedUrl: null,
    keywords: [
      "remove background",
      "background remover",
      "remove image background",
      "transparent background",
      "cut out background",
      "bg remover",
    ],
    trending: true,
    new: true,
    featured: true,
    monthlySearches: 5_400_000,
    cpc: 8,
    relatedTools: ["upscale-image", "photo-editor", "watermark-image"],
  },
  {
    id: "watermark-image",
    name: "Watermark Image",
    description:
      "Add text or image watermarks to photos. Control typography, transparency and position.",
    longDescription:
      "Stamp your photos with text or logo watermarks for copyright protection or branding. Tune font, size, color, opacity, rotation, and tile across the image. Bulk-apply the same watermark to dozens of photos in one go.",
    category: "Image Tools",
    icon: "Stamp",
    href: "/tools/watermark-image",
    externalHref: null,
    embedUrl: null,
    keywords: [
      "watermark image",
      "add watermark",
      "watermark photo",
      "image watermark",
      "add text to image",
      "photo watermark",
    ],
    trending: false,
    new: true,
    featured: false,
    monthlySearches: 720_000,
    cpc: 3,
    relatedTools: ["photo-editor", "compress-image", "blur-face"],
  },
  {
    id: "meme-generator",
    name: "Meme Generator",
    description:
      "Create custom memes online. Caption popular templates or upload your own image.",
    longDescription:
      "Pick from 20+ popular meme templates (Drake, Distracted Boyfriend, Two Buttons, etc.) or upload your own image. Edit top and bottom text with the classic Impact font, adjust placement, and download a high-resolution PNG ready to share.",
    category: "Image Tools",
    icon: "Laugh",
    href: "/tools/meme-generator",
    externalHref: null,
    embedUrl: null,
    keywords: [
      "meme generator",
      "make a meme",
      "meme maker",
      "create meme",
      "custom meme",
      "meme creator",
      "free meme maker",
    ],
    trending: true,
    new: true,
    featured: false,
    monthlySearches: 1_900_000,
    cpc: 2,
    relatedTools: ["photo-editor", "convert-from-jpg", "watermark-image"],
  },
  {
    id: "rotate-image",
    name: "Image Rotator",
    description:
      "Rotate JPG, PNG or GIF images in bulk. Rotate only landscape or portrait images selectively.",
    longDescription:
      "Rotate single images or whole batches by 90°, 180°, 270°, or any custom angle. Filter the batch to only landscape or only portrait orientation so you can fix camera-tilt issues without touching photos that are already correct.",
    category: "Image Tools",
    icon: "RotateCw",
    href: "/tools/rotate-image",
    externalHref: null,
    embedUrl: null,
    keywords: [
      "rotate image",
      "rotate photo",
      "flip image",
      "rotate jpg",
      "rotate png",
      "image rotation",
      "flip photo",
    ],
    trending: false,
    new: true,
    featured: false,
    monthlySearches: 540_000,
    cpc: 2,
    relatedTools: ["crop-image", "resize-image", "compress-image"],
  },
  {
    id: "html-to-image",
    name: "HTML to Image",
    description:
      "Convert any webpage URL or HTML code to JPG or PNG image with one click.",
    longDescription:
      "Capture any webpage (by URL) or arbitrary HTML/CSS snippet as a high-resolution JPG or PNG. Choose viewport size, full-page vs above-the-fold, and let it run JavaScript before snapshotting. Useful for social cards, design archives, and bug reports.",
    category: "Image Tools",
    icon: "Globe",
    href: "/tools/html-to-image",
    externalHref: null,
    embedUrl: null,
    keywords: [
      "html to image",
      "webpage to image",
      "url to image",
      "screenshot website",
      "html to jpg",
      "webpage screenshot",
      "website to png",
    ],
    trending: false,
    new: true,
    featured: false,
    monthlySearches: 290_000,
    cpc: 4,
    relatedTools: ["meta-tag-generator", "qr-code-generator", "photo-editor"],
  },
  {
    id: "blur-face",
    name: "Face Blur",
    description:
      "Automatically detect and blur faces in photos. Also blur licence plates and sensitive objects.",
    longDescription:
      "AI-driven face detection that anonymizes everyone in a photo with a single click. Detects and blurs license plates and other sensitive objects too. Adjustable blur radius and pixelation. All processing runs locally so private images never leave your device.",
    category: "Image Tools",
    icon: "EyeOff",
    href: "/tools/blur-face",
    externalHref: null,
    embedUrl: null,
    keywords: [
      "blur face",
      "face blur",
      "blur faces in photo",
      "anonymize photo",
      "blur license plate",
      "privacy photo editor",
      "face detection blur",
    ],
    trending: false,
    new: true,
    featured: false,
    monthlySearches: 360_000,
    cpc: 3,
    relatedTools: ["remove-background", "watermark-image", "photo-editor"],
  },

  // ─── Video Tools ────────────────────────────────────────────────────────
  {
    id: "video-compressor",
    name: "Video Compressor",
    description:
      "Compress MP4, MOV, WebM and more by up to 80% without uploading. Runs in your browser via ffmpeg.wasm.",
    longDescription:
      "Reduce video file size with an H.264 re-encode that runs entirely in your browser. Pick a quality preset (Low / Medium / High) and download a standard MP4 that plays everywhere. No upload, no signup, no watermark.",
    category: "Video Tools",
    icon: "Film",
    href: "/tools/video-compressor",
    externalHref: null,
    embedUrl: null,
    keywords: [
      "video compressor",
      "compress video online",
      "compress mp4",
      "shrink video",
      "reduce video size",
      "free video compressor",
    ],
    trending: true,
    new: true,
    featured: true,
    monthlySearches: 1_200_000,
    cpc: 6,
    relatedTools: ["video-trimmer", "video-resizer", "mp4-to-webm"],
  },
  {
    id: "video-trimmer",
    name: "Video Trimmer",
    description:
      "Cut a clean section out of any MP4, MOV, WebM or MKV with lossless stream-copy. No re-encode, no quality loss.",
    longDescription:
      "Trim videos in your browser using ffmpeg's stream-copy mode — the cut bytes are bit-identical to the source. Drag the timeline, type timestamps, or both. Output keeps the original container.",
    category: "Video Tools",
    icon: "Scissors",
    href: "/tools/video-trimmer",
    externalHref: null,
    embedUrl: null,
    keywords: [
      "video trimmer",
      "trim video online",
      "cut video",
      "crop video",
      "trim mp4",
      "free video trimmer",
    ],
    trending: true,
    new: true,
    featured: true,
    monthlySearches: 880_000,
    cpc: 4,
    relatedTools: ["video-compressor", "mute-video", "video-resizer"],
  },
  {
    id: "video-to-gif",
    name: "Video to GIF",
    description:
      "Turn any short video clip into an animated GIF with configurable fps, width, and length. Browser-side, no watermark.",
    longDescription:
      "Convert MP4, MOV, WebM and other videos to animated GIFs with a two-pass palette workflow for clean colours. Pick the start time, length (1–30 s), frame rate, and width — the conversion happens locally with ffmpeg.wasm.",
    category: "Video Tools",
    icon: "ImagePlay",
    href: "/tools/video-to-gif",
    externalHref: null,
    embedUrl: null,
    keywords: [
      "video to gif",
      "mp4 to gif",
      "mov to gif",
      "convert video to gif",
      "online gif maker",
      "free gif converter",
    ],
    trending: true,
    new: true,
    featured: true,
    monthlySearches: 1_400_000,
    cpc: 4,
    relatedTools: ["video-compressor", "video-trimmer", "video-frame-extractor"],
  },
  {
    id: "mp4-to-webm",
    name: "MP4 to WebM",
    description:
      "Convert MP4, MOV, and MKV videos to WebM (VP8) in your browser. Smaller files for HTML5 video, no upload required.",
    longDescription:
      "Encode MP4, MOV, or MKV inputs as WebM with VP8 video and Vorbis audio. Pick a quality preset and download a file that's typically 25–35% smaller than the equivalent H.264 MP4.",
    category: "Video Tools",
    icon: "FileVideo",
    href: "/tools/mp4-to-webm",
    externalHref: null,
    embedUrl: null,
    keywords: [
      "mp4 to webm",
      "convert mp4 to webm",
      "webm converter",
      "free video converter",
      "html5 video format",
    ],
    trending: false,
    new: true,
    featured: false,
    monthlySearches: 420_000,
    cpc: 5,
    relatedTools: ["video-compressor", "video-resizer", "extract-audio-from-video"],
  },
  {
    id: "extract-audio-from-video",
    name: "Extract Audio from Video",
    description:
      "Pull the audio track out of any video as MP3 or AAC. Browser-side, no upload, no watermark.",
    longDescription:
      "Save the audio from a video file as a standalone MP3 (universal compatibility) or AAC (smaller files at the same quality). Works on MP4, MOV, WebM, MKV, AVI and more. The video never leaves your browser.",
    category: "Video Tools",
    icon: "AudioLines",
    href: "/tools/extract-audio-from-video",
    externalHref: null,
    embedUrl: null,
    keywords: [
      "extract audio from video",
      "mp4 to mp3",
      "video to mp3",
      "mov to mp3",
      "extract sound from video",
      "free audio extractor",
    ],
    trending: true,
    new: true,
    featured: true,
    monthlySearches: 1_100_000,
    cpc: 5,
    relatedTools: ["mute-video", "video-trimmer", "video-compressor"],
  },
  {
    id: "video-frame-extractor",
    name: "Video Frame Extractor",
    description:
      "Save every frame, every N seconds, or a single frame from a video as PNG or JPG. ZIP download for multi-frame jobs.",
    longDescription:
      "Extract still frames from any video file in three modes: single timestamp, every N seconds, or all frames in a time range. PNG (lossless) or JPG output, packaged as a ZIP when more than one frame is produced.",
    category: "Video Tools",
    icon: "Camera",
    href: "/tools/video-frame-extractor",
    externalHref: null,
    embedUrl: null,
    keywords: [
      "video frame extractor",
      "extract frames from video",
      "video to png",
      "video to images",
      "still frame from video",
      "mp4 frame extractor",
    ],
    trending: false,
    new: true,
    featured: false,
    monthlySearches: 280_000,
    cpc: 3,
    relatedTools: ["video-to-gif", "video-trimmer", "video-compressor"],
  },
  {
    id: "mute-video",
    name: "Mute Video",
    description:
      "Remove the audio track from a video without re-encoding. Lossless, instant, browser-side.",
    longDescription:
      "Strip audio from MP4, MOV, WebM and other videos using ffmpeg's stream-copy mode. The video track is bit-identical to the source; only the audio is gone. Great for removing copyrighted music before social uploads.",
    category: "Video Tools",
    icon: "VolumeX",
    href: "/tools/mute-video",
    externalHref: null,
    embedUrl: null,
    keywords: [
      "mute video",
      "remove audio from video",
      "silent video",
      "remove sound from video",
      "mp4 mute online",
    ],
    trending: false,
    new: true,
    featured: false,
    monthlySearches: 540_000,
    cpc: 3,
    relatedTools: ["extract-audio-from-video", "video-trimmer", "video-compressor"],
  },
  {
    id: "video-resizer",
    name: "Video Resizer",
    description:
      "Resize videos for Reel, TikTok, YouTube Short, or any custom dimensions. Aspect-ratio lock and presets included.",
    longDescription:
      "Resize MP4, MOV, WebM, and MKV files to social-media dimensions or a custom width and height. Lock aspect ratio (with letterbox / pillarbox padding) or stretch to fill. Output is an H.264 MP4.",
    category: "Video Tools",
    icon: "Maximize2",
    href: "/tools/video-resizer",
    externalHref: null,
    embedUrl: null,
    keywords: [
      "video resizer",
      "resize video online",
      "video size for reel",
      "video size for tiktok",
      "youtube short size",
      "resize mp4",
    ],
    trending: true,
    new: true,
    featured: true,
    monthlySearches: 760_000,
    cpc: 4,
    relatedTools: ["video-compressor", "video-trimmer", "mp4-to-webm"],
  },

  // ─── Productivity Tools ─────────────────────────────────────────────────
  {
    id: "barcode-generator",
    name: "Barcode Generator",
    description:
      "Generate Code 128, EAN-13, UPC, Code 39 and 5 more barcode formats free in your browser. Download as PNG or SVG.",
    longDescription:
      "Free barcode generator supporting Code 128, EAN-13, EAN-8, UPC-A, UPC-E, Code 39, ITF-14, ITF, MSI, and Pharmacode. Adjust bar height, line width, and toggle the human-readable text. Export as crisp PNG or scalable SVG. Runs entirely in your browser using JsBarcode.",
    category: "Productivity Tools",
    icon: "Barcode",
    href: "/tools/barcode-generator",
    externalHref: null,
    embedUrl: null,
    keywords: [
      "barcode generator",
      "code 128 generator",
      "ean-13 generator",
      "upc generator",
      "barcode maker",
      "free barcode generator",
    ],
    trending: true,
    new: true,
    featured: true,
    monthlySearches: 680_000,
    cpc: 5,
    relatedTools: ["qr-code-generator", "invoice-generator", "countdown-timer"],
  },
  {
    id: "pomodoro-timer",
    name: "Pomodoro Timer",
    description:
      "Free Pomodoro timer with task log. Customisable 25/5/15 intervals, sound + desktop notifications, and persistent local storage.",
    longDescription:
      "Online Pomodoro timer that drives focused 25-minute work intervals separated by short breaks, with a longer break after every four cycles. Built-in task log tracks how many Pomodoros each task takes. Settings, tasks, and Pomodoro counts persist in local storage.",
    category: "Productivity Tools",
    icon: "Timer",
    href: "/tools/pomodoro-timer",
    externalHref: null,
    embedUrl: null,
    keywords: [
      "pomodoro timer",
      "online pomodoro",
      "focus timer",
      "25 minute timer",
      "study timer",
      "pomodoro technique",
    ],
    trending: true,
    new: true,
    featured: true,
    monthlySearches: 920_000,
    cpc: 3,
    relatedTools: ["countdown-timer", "barcode-generator", "invoice-generator"],
  },
  {
    id: "countdown-timer",
    name: "Countdown Timer",
    description:
      "Count down to any date with a custom title, accent colour, and end-of-countdown message. Shareable URL and iframe embed.",
    longDescription:
      "Free online countdown timer to any future date and time. Adds days, hours, minutes, and seconds remaining, updated every second. Pick an accent colour and add a custom message that appears when the countdown reaches zero. Every configuration produces a permanent shareable URL and an iframe snippet you can embed on your own site.",
    category: "Productivity Tools",
    icon: "Clock",
    href: "/tools/countdown-timer",
    externalHref: null,
    embedUrl: null,
    keywords: [
      "countdown timer",
      "countdown to date",
      "online countdown",
      "embeddable countdown",
      "wedding countdown",
      "launch countdown",
    ],
    trending: true,
    new: true,
    featured: true,
    monthlySearches: 540_000,
    cpc: 3,
    relatedTools: ["pomodoro-timer", "barcode-generator", "invoice-generator"],
  },
  {
    id: "invoice-generator",
    name: "Invoice Generator",
    description:
      "Free branded invoice generator. Add your logo, fill the form, download a clean PDF. Multi-currency, tax + discount, line-item totals.",
    longDescription:
      "Online invoice generator for freelancers and small businesses. Auto-calculating line items, tax, and discount. Multi-currency formatting via the browser's Intl API. Optional logo upload embeds directly into the PDF — your client and pricing details stay on your device.",
    category: "Productivity Tools",
    icon: "Receipt",
    href: "/tools/invoice-generator",
    externalHref: null,
    embedUrl: null,
    keywords: [
      "invoice generator",
      "free invoice maker",
      "online invoice",
      "pdf invoice",
      "freelance invoice",
      "branded invoice template",
    ],
    trending: true,
    new: true,
    featured: true,
    monthlySearches: 1_300_000,
    cpc: 12,
    relatedTools: ["pomodoro-timer", "countdown-timer", "barcode-generator"],
  },

  // ─── Developer Tools (in-house) ────────────────────────────────────────
  {
    id: "jwt-decoder",
    name: "JWT Decoder",
    description:
      "Decode JWT tokens free in your browser. See header, payload, and signature, plus verify HS256/HS384/HS512 signatures with a shared secret.",
    longDescription:
      "Free JWT decoder + HMAC signature verifier. Paste any JWT to see its decoded header and payload, with standard claims highlighted. For HS256/HS384/HS512 tokens, paste the shared secret and the verifier confirms the signature is valid using the WebCrypto API. Asymmetric (RS256/ES256) tokens are decoded but not verified — pasting a private key into a browser tool is risky.",
    category: "Developer Tools",
    icon: "KeyRound",
    href: "/tools/jwt-decoder",
    externalHref: null,
    embedUrl: null,
    keywords: ["jwt decoder", "jwt parser", "jwt debugger", "decode jwt", "verify jwt signature"],
    trending: true,
    new: true,
    featured: true,
    monthlySearches: 540_000,
    cpc: 8,
    relatedTools: ["hash-generator", "uuid-generator", "base64-encoder"],
  },
  {
    id: "uuid-generator",
    name: "UUID Generator",
    description:
      "Generate v1, v4, or v7 UUIDs free in your browser. Single or batches up to 1,000. Copy or download as .txt.",
    longDescription:
      "Online UUID generator supporting v1 (timestamp + node), v4 (random, default), and v7 (sortable + opaque, recommended for new systems). Generate one UUID or batches of up to 1,000 at once. Randomness comes from the browser's WebCrypto API. Copy individual UUIDs, copy the entire batch, or download as a plain text file.",
    category: "Developer Tools",
    icon: "Fingerprint",
    href: "/tools/uuid-generator",
    externalHref: null,
    embedUrl: null,
    keywords: ["uuid generator", "uuid v4", "uuid v7", "uuid v1", "guid generator"],
    trending: true,
    new: true,
    featured: true,
    monthlySearches: 720_000,
    cpc: 4,
    relatedTools: ["jwt-decoder", "hash-generator", "password-generator"],
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    description:
      "Test JavaScript regex patterns live in your browser. Live match highlighting, named + numbered capture groups, all standard flags.",
    longDescription:
      "Live regex tester for JavaScript (ECMAScript) flavour patterns. Toggle the g, i, m, s, u, y flags, paste your test text, and see matches highlight in the source plus a list of every match with its capture groups. Times out at 2 seconds to protect against catastrophic backtracking. Runs entirely in your browser.",
    category: "Developer Tools",
    icon: "Regex",
    href: "/tools/regex-tester",
    externalHref: null,
    embedUrl: null,
    keywords: ["regex tester", "regex online", "regular expression tester", "javascript regex"],
    trending: true,
    new: true,
    featured: true,
    monthlySearches: 980_000,
    cpc: 5,
    relatedTools: ["json-formatter", "html-formatter", "sql-formatter"],
  },
  {
    id: "yaml-to-json",
    name: "YAML ↔ JSON",
    description:
      "Convert YAML to JSON or JSON to YAML free in your browser. Live preview, YAML 1.2 support, anchors and aliases handled.",
    longDescription:
      "Bi-directional YAML and JSON converter powered by js-yaml (YAML 1.2). Paste YAML on the left, see the equivalent JSON appear instantly on the right — or flip the direction with one click. Anchors and aliases are resolved. Works for Kubernetes, GitHub Actions, Docker Compose, Ansible, and any other YAML 1.2 source.",
    category: "Developer Tools",
    icon: "Braces",
    href: "/tools/yaml-to-json",
    externalHref: null,
    embedUrl: null,
    keywords: ["yaml to json", "json to yaml", "yaml converter", "yaml parser"],
    trending: true,
    new: true,
    featured: true,
    monthlySearches: 480_000,
    cpc: 4,
    relatedTools: ["json-formatter", "csv-to-json", "html-formatter"],
  },
  {
    id: "csv-to-json",
    name: "CSV to JSON",
    description:
      "Convert CSV to JSON free in your browser. Auto-detects separators (comma, semicolon, tab, pipe), handles quoted values, header toggle.",
    longDescription:
      "Online CSV to JSON converter. Paste a CSV table on the left and an array of JSON objects appears on the right. Auto-detects comma, semicolon, tab, or pipe separators (override available). Honours RFC 4180 quoting rules so embedded separators and newlines are handled correctly. Toggle whether the first row is headers.",
    category: "Developer Tools",
    icon: "FileSpreadsheet",
    href: "/tools/csv-to-json",
    externalHref: null,
    embedUrl: null,
    keywords: ["csv to json", "csv parser", "csv converter", "online csv"],
    trending: true,
    new: true,
    featured: true,
    monthlySearches: 660_000,
    cpc: 4,
    relatedTools: ["yaml-to-json", "json-formatter", "html-formatter"],
  },
  {
    id: "cron-expression-builder",
    name: "Cron Expression Builder",
    description:
      "Build cron expressions visually, see plain-English description, and preview the next 5 fire times in your local timezone.",
    longDescription:
      "Visual cron expression builder. Pick a preset (every hour, weekdays at 8 AM, every Sunday at midnight, etc.) or type the expression directly — the tool produces a plain-English description and the next 5 fire times computed in your local timezone. Supports the standard 5-field Unix cron syntax used by crontab, GitHub Actions, Render, and most schedulers.",
    category: "Developer Tools",
    icon: "CalendarClock",
    href: "/tools/cron-expression-builder",
    externalHref: null,
    embedUrl: null,
    keywords: ["cron expression", "cron builder", "cron syntax", "crontab", "online cron"],
    trending: true,
    new: true,
    featured: true,
    monthlySearches: 320_000,
    cpc: 3,
    relatedTools: ["countdown-timer", "regex-tester", "json-formatter"],
  },
  {
    id: "html-formatter",
    name: "HTML Formatter",
    description:
      "Pretty-print or minify HTML free in your browser. Embedded JS and CSS are formatted too. Configurable indent.",
    longDescription:
      "HTML formatter and minifier powered by js-beautify. Pretty-print mode adds clean indentation (configurable width), preserves the document structure, and formats embedded JavaScript and CSS with their own parsers. Minify mode collapses whitespace and strips comments to produce production-ready compact HTML. Runs entirely in your browser.",
    category: "Developer Tools",
    icon: "FileCode",
    href: "/tools/html-formatter",
    externalHref: null,
    embedUrl: null,
    keywords: ["html formatter", "html beautifier", "html minifier", "pretty print html"],
    trending: false,
    new: true,
    featured: false,
    monthlySearches: 290_000,
    cpc: 4,
    relatedTools: ["json-formatter", "sql-formatter", "yaml-to-json"],
  },
  {
    id: "sql-formatter",
    name: "SQL Formatter",
    description:
      "Format SQL queries free in your browser. Postgres, MySQL, BigQuery, Snowflake, Redshift, SQLite, T-SQL and more. Configurable indent and keyword case.",
    longDescription:
      "Multi-dialect SQL formatter. Pick from Standard SQL, PostgreSQL, MySQL, MariaDB, BigQuery, Snowflake, Redshift, SQLite, Db2, Trino/Presto, or T-SQL. Configure indentation width and keyword case (UPPER, lower, preserve). Powered by the sql-formatter library. No connection to any database is made — formatting only.",
    category: "Developer Tools",
    icon: "Database",
    href: "/tools/sql-formatter",
    externalHref: null,
    embedUrl: null,
    keywords: ["sql formatter", "sql beautifier", "format sql", "postgres formatter"],
    trending: true,
    new: true,
    featured: true,
    monthlySearches: 450_000,
    cpc: 5,
    relatedTools: ["json-formatter", "html-formatter", "regex-tester"],
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    description:
      "Generate MD5, SHA-1, SHA-256, and SHA-512 hashes of text or files free in your browser. WebCrypto-backed.",
    longDescription:
      "Online hash generator for MD5, SHA-1, SHA-256, and SHA-512. Hash text or files (any size — files are streamed directly from the browser to the WebCrypto API). MD5 uses a small JS implementation since browsers don't expose it natively. Useful for verifying downloads against published checksums, deduplication, and (for SHA-256/512) cryptographic integrity checks.",
    category: "Developer Tools",
    icon: "Hash",
    href: "/tools/hash-generator",
    externalHref: null,
    embedUrl: null,
    keywords: ["hash generator", "md5 generator", "sha-256 generator", "sha-512", "online hash"],
    trending: true,
    new: true,
    featured: true,
    monthlySearches: 580_000,
    cpc: 4,
    relatedTools: ["jwt-decoder", "uuid-generator", "password-generator"],
  },
  {
    id: "color-converter",
    name: "Colour Converter",
    description:
      "Convert between HEX, RGB, HSL, and the 147 named CSS colours. Live preview swatch and one-click copy.",
    longDescription:
      "Free colour converter for designers and developers. Type any HEX (3, 4, 6, or 8 digit), RGB / RGBA, HSL / HSLA, or CSS named colour and the others update live. Includes a preview swatch, alpha channel preservation, and the closest CSS named colour for any input. 147 named colours from CSS Color Module Level 4.",
    category: "Developer Tools",
    icon: "Palette",
    href: "/tools/color-converter",
    externalHref: null,
    embedUrl: null,
    keywords: ["color converter", "hex to rgb", "rgb to hex", "hex to hsl", "css color names"],
    trending: true,
    new: true,
    featured: true,
    monthlySearches: 870_000,
    cpc: 4,
    relatedTools: ["html-formatter", "regex-tester", "json-formatter"],
  },

  // ─── Audio Tools ───────────────────────────────────────────────────────
  {
    id: "mp3-cutter",
    name: "MP3 Cutter",
    description:
      "Cut and trim MP3, WAV, OGG, FLAC and more free in your browser. Lossless stream-copy — no re-encoding, no quality loss.",
    longDescription:
      "Online MP3 cutter and audio trimmer. Drag the start/end handles or type timestamps, then cut a clean section out of any audio file. Uses ffmpeg's stream-copy mode so the output is bit-identical to the source — perfect for ringtones, podcast clips, and samples. Runs entirely in your browser.",
    category: "Audio Tools",
    icon: "Scissors",
    href: "/tools/mp3-cutter",
    externalHref: null,
    embedUrl: null,
    keywords: ["mp3 cutter", "audio trimmer", "cut mp3", "trim audio online", "mp3 trimmer"],
    trending: true,
    new: true,
    featured: true,
    monthlySearches: 740_000,
    cpc: 4,
    relatedTools: ["audio-converter", "voice-recorder", "bpm-detector"],
  },
  {
    id: "audio-converter",
    name: "Audio Converter",
    description:
      "Convert audio between MP3, WAV, OGG, FLAC, AAC and OPUS free in your browser. Powered by ffmpeg.wasm.",
    longDescription:
      "Free audio converter supporting MP3, WAV, OGG (Vorbis), FLAC, AAC/M4A, and OPUS as both input and output. Lossless formats convert without loss; lossy formats re-encode at transparent default bitrates. The transcode runs in your browser via ffmpeg.wasm — your audio never leaves your device.",
    category: "Audio Tools",
    icon: "AudioLines",
    href: "/tools/audio-converter",
    externalHref: null,
    embedUrl: null,
    keywords: ["audio converter", "mp3 converter", "wav to mp3", "flac to mp3", "convert audio online"],
    trending: true,
    new: true,
    featured: true,
    monthlySearches: 920_000,
    cpc: 5,
    relatedTools: ["mp3-cutter", "voice-recorder", "bpm-detector"],
  },
  {
    id: "voice-recorder",
    name: "Voice Recorder",
    description:
      "Record your voice free in your browser with a live waveform. Download as WebM or MP3. No signup, no upload.",
    longDescription:
      "Online voice recorder built on the MediaRecorder API. Capture audio from your microphone with a live waveform display, play it back, and download as WebM/Opus (small file) or convert to MP3. The recording exists only in your browser tab — nothing is uploaded to a server.",
    category: "Audio Tools",
    icon: "Mic",
    href: "/tools/voice-recorder",
    externalHref: null,
    embedUrl: null,
    keywords: ["voice recorder", "online voice recorder", "audio recorder", "record voice", "mic recorder"],
    trending: true,
    new: true,
    featured: true,
    monthlySearches: 1_100_000,
    cpc: 4,
    relatedTools: ["audio-converter", "mp3-cutter", "bpm-detector"],
  },
  {
    id: "bpm-detector",
    name: "BPM Detector",
    description:
      "Detect the BPM (tempo) of any song free in your browser. Drop an MP3, WAV, OGG or FLAC and get beats per minute.",
    longDescription:
      "Free BPM detector that finds a song's tempo using the Web Audio API. The audio is decoded to PCM, energy peaks (kick drums, snares) are detected, and the dominant inter-peak interval is converted to beats per minute. Accurate within ±2 BPM for music with a clear beat.",
    category: "Audio Tools",
    icon: "AudioWaveform",
    href: "/tools/bpm-detector",
    externalHref: null,
    embedUrl: null,
    keywords: ["bpm detector", "bpm counter", "find bpm", "song tempo", "beats per minute"],
    trending: true,
    new: true,
    featured: true,
    monthlySearches: 480_000,
    cpc: 3,
    relatedTools: ["audio-converter", "mp3-cutter", "voice-recorder"],
  },
];

export const TOOLS_BY_ID: Record<string, Tool> = TOOLS.reduce(
  (acc, tool) => {
    acc[tool.id] = tool;
    return acc;
  },
  {} as Record<string, Tool>
);

export function getToolBySlug(slug: string): Tool | undefined {
  return TOOLS_BY_ID[slug];
}

export function getToolsByCategory(category: string): Tool[] {
  return TOOLS.filter((tool) => tool.category === category);
}

export function getFeaturedTools(): Tool[] {
  return TOOLS.filter((tool) => tool.featured);
}

export function getTrendingTools(): Tool[] {
  return TOOLS.filter((tool) => tool.trending);
}

export function getNewTools(): Tool[] {
  return TOOLS.filter((tool) => tool.new);
}
